version: '3'

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 5000
    ports:
      - "5000:5000"

#  db:
#    image: postgres:15
#    environment:
#      POSTGRES_PASSWORD: 12345
#      POSTGRES_DB: NewDB
